// ********RoostGPT********
/*
Test generated by RoostGPT for test homeloan-AT using AI Type Open AI and AI Model gpt-4o

Test generated for /api/loan-applications/{applicationId}/offer/accept_put for http method type PUT in rest-assured framework

RoostTestHash=0555f52776

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test a valid request with proper path and auth token",
    "Execution": {
      "Arrange": "Prepare a valid 'applicationId' and valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/{applicationId}/offer/accept with correct headers",
      "Assert": "Check for 200 status and response body contains confirmationMessage, acceptanceTimestamp, and nextSteps"
    },
    "Validation": "Ensures API successfully returns correct response with valid input"
  },
  {
    "ScenarioID": "2",
    "TestName": "testMissingApplicationIdReturns404",
    "Description": "Test request with missing applicationId in the path",
    "Execution": {
      "Arrange": "Prepare a valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications//offer/accept with correct headers",
      "Assert": "Check for 404 status"
    },
    "Validation": "Ensures API returns 404 when applicationId is missing"
  },
  {
    "ScenarioID": "3",
    "TestName": "testInvalidApplicationIdReturns404",
    "Description": "Test request with invalid applicationId",
    "Execution": {
      "Arrange": "Prepare an invalid 'applicationId' and valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/invalidId/offer/accept with correct headers",
      "Assert": "Check for 404 status"
    },
    "Validation": "Ensures API returns 404 when applicationId is invalid"
  },
  {
    "ScenarioID": "4",
    "TestName": "testMissingAuthTokenReturns401",
    "Description": "Test request without Bearer token",
    "Execution": {
      "Arrange": "Prepare a valid 'applicationId'",
      "Act": "Send PUT request to /api/loan-applications/{applicationId}/offer/accept without Bearer token",
      "Assert": "Check for 401 status"
    },
    "Validation": "Ensures API returns 401 when Bearer token is missing"
  },
  {
    "ScenarioID": "5",
    "TestName": "testInvalidAuthTokenReturns401",
    "Description": "Test request with invalid Bearer token",
    "Execution": {
      "Arrange": "Prepare a valid 'applicationId' and invalid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/{applicationId}/offer/accept with invalid Bearer token",
      "Assert": "Check for 401 status"
    },
    "Validation": "Ensures API returns 401 when Bearer token is invalid"
  },
  {
    "ScenarioID": "6",
    "TestName": "testMalformedApplicationIdReturns404",
    "Description": "Test request with malformed applicationId",
    "Execution": {
      "Arrange": "Prepare a malformed 'applicationId' (e.g., special characters) and valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/!@#$%^&*/offer/accept with correct headers",
      "Assert": "Check for 404 status"
    },
    "Validation": "Ensures API returns 404 when applicationId is malformed"
  },
  {
    "ScenarioID": "7",
    "TestName": "testEmptyApplicationIdReturns404",
    "Description": "Test request with empty applicationId",
    "Execution": {
      "Arrange": "Prepare an empty 'applicationId' and valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications//offer/accept with correct headers",
      "Assert": "Check for 404 status"
    },
    "Validation": "Ensures API returns 404 when applicationId is empty"
  }
]

*/

// ********RoostGPT********
package com.medeiros.RoostTest;
applicationId,baseUrl
import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class ApiLoanapplicationsApplicationIdOfferAcceptPutTest {

    List<JSONObject> testCases = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/com/medeiros/RoostTest/api_loan-applications_applicationId_offer_acceptPutTest.JSON");
    }


    @Test
    public void ApiLoanapplicationsApplicationIdOfferAcceptPut_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = "{baseUrl}";

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/api/loan-applications/{applicationId}/offer/accept";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "/var/tmp/Roost/RoostGPT/homeloan-AT/b0fc1826-0d80-4c1c-84b2-8595fd39aa80/20251027-073651-roost-vscode-api-musicblender-java-test.yaml";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("put".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "put");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: ApiLoanapplicationsApplicationIdOfferAcceptPut_Test\n", testNumber++);
            System.out.println("Request: PUT " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }
}
