// ********RoostGPT********
/*
Test generated by RoostGPT for test homeloan-AT using AI Type Open AI and AI Model gpt-4o

Test generated for /api/loan-applications/resume_get for http method type GET in rest-assured framework

RoostTestHash=db25e0b0b0

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test a valid request with proper query params and valid auth token",
    "Execution": {
      "Arrange": "Prepare valid 'referenceNumber' and 'emailAddress' query params and a valid auth token",
      "Act": "Send GET request to /api/loan-applications/resume with correct headers and params",
      "Assert": "Check for 200 status and response body contains applicationId, completedSections, personalInfo, and employment"
    },
    "Validation": "Ensures API successfully returns correct response with valid input"
  },
  {
    "ScenarioID": "2",
    "TestName": "testMissingReferenceNumberReturns400",
    "Description": "Test request with missing 'referenceNumber' query param",
    "Execution": {
      "Arrange": "Prepare a valid 'emailAddress' query param and a valid auth token",
      "Act": "Send GET request to /api/loan-applications/resume without 'referenceNumber'",
      "Assert": "Check for 400 status indicating missing required parameter"
    },
    "Validation": "Ensures API returns error when required 'referenceNumber' is missing"
  },
  {
    "ScenarioID": "3",
    "TestName": "testMissingEmailAddressReturns400",
    "Description": "Test request with missing 'emailAddress' query param",
    "Execution": {
      "Arrange": "Prepare a valid 'referenceNumber' query param and a valid auth token",
      "Act": "Send GET request to /api/loan-applications/resume without 'emailAddress'",
      "Assert": "Check for 400 status indicating missing required parameter"
    },
    "Validation": "Ensures API returns error when required 'emailAddress' is missing"
  },
  {
    "ScenarioID": "4",
    "TestName": "testInvalidReferenceNumberFormatReturns400",
    "Description": "Test request with invalid format for 'referenceNumber'",
    "Execution": {
      "Arrange": "Prepare an invalid 'referenceNumber' (e.g., numeric) and a valid 'emailAddress' and auth token",
      "Act": "Send GET request to /api/loan-applications/resume with invalid 'referenceNumber'",
      "Assert": "Check for 400 status indicating invalid parameter format"
    },
    "Validation": "Ensures API returns error for invalid 'referenceNumber' format"
  },
  {
    "ScenarioID": "5",
    "TestName": "testInvalidEmailAddressFormatReturns400",
    "Description": "Test request with invalid format for 'emailAddress'",
    "Execution": {
      "Arrange": "Prepare a valid 'referenceNumber' and an invalid 'emailAddress' (e.g., missing '@') and a valid auth token",
      "Act": "Send GET request to /api/loan-applications/resume with invalid 'emailAddress'",
      "Assert": "Check for 400 status indicating invalid parameter format"
    },
    "Validation": "Ensures API returns error for invalid 'emailAddress' format"
  },
  {
    "ScenarioID": "6",
    "TestName": "testApplicationNotFoundReturns404",
    "Description": "Test request with non-existent 'referenceNumber' and 'emailAddress'",
    "Execution": {
      "Arrange": "Prepare non-existent 'referenceNumber' and 'emailAddress' with a valid auth token",
      "Act": "Send GET request to /api/loan-applications/resume with non-existent data",
      "Assert": "Check for 404 status indicating application not found"
    },
    "Validation": "Ensures API returns 404 when application is not found"
  },
  {
    "ScenarioID": "7",
    "TestName": "testMissingAuthTokenReturns401",
    "Description": "Test request without an authorization token",
    "Execution": {
      "Arrange": "Prepare valid 'referenceNumber' and 'emailAddress' query params",
      "Act": "Send GET request to /api/loan-applications/resume without auth token",
      "Assert": "Check for 401 status indicating missing authorization"
    },
    "Validation": "Ensures API requires authorization token"
  },
  {
    "ScenarioID": "8",
    "TestName": "testInvalidAuthTokenReturns401",
    "Description": "Test request with an invalid authorization token",
    "Execution": {
      "Arrange": "Prepare valid 'referenceNumber' and 'emailAddress' query params and an invalid auth token",
      "Act": "Send GET request to /api/loan-applications/resume with invalid auth token",
      "Assert": "Check for 401 status indicating invalid authorization"
    },
    "Validation": "Ensures API returns error for invalid authorization token"
  },
  {
    "ScenarioID": "9",
    "TestName": "testEmptyQueryParamsReturns400",
    "Description": "Test request with empty query parameters",
    "Execution": {
      "Arrange": "Prepare empty 'referenceNumber' and 'emailAddress' query params with a valid auth token",
      "Act": "Send GET request to /api/loan-applications/resume with empty query params",
      "Assert": "Check for 400 status indicating invalid parameters"
    },
    "Validation": "Ensures API returns error for empty query parameters"
  }
]

*/

// ********RoostGPT********
package com.medeiros.RoostTest;
baseUrl
import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class ApiLoanapplicationsResumeGetTest {

    List<JSONObject> testCases = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/com/medeiros/RoostTest/api_loan-applications_resumeGetTest.JSON");
    }


    @Test
    public void ApiLoanapplicationsResumeGet_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = "{baseUrl}";

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/api/loan-applications/resume";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "/var/tmp/Roost/RoostGPT/homeloan-AT/b0fc1826-0d80-4c1c-84b2-8595fd39aa80/20251027-073651-roost-vscode-api-musicblender-java-test.yaml";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("get".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "get");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: ApiLoanapplicationsResumeGet_Test\n", testNumber++);
            System.out.println("Request: GET " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }
}
