// ********RoostGPT********
/*
Test generated by RoostGPT for test homeloan-AT using AI Type Open AI and AI Model gpt-4o

Test generated for /api/loan-applications/{applicationId}/offer/reject_put for http method type PUT in rest-assured framework

RoostTestHash=1373f5dd18

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test rejecting a loan offer with a valid applicationId and valid auth token",
    "Execution": {
      "Arrange": "Prepare a valid applicationId and a valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/{applicationId}/offer/reject with correct headers",
      "Assert": "Check for 200 status and response body contains confirmationMessage, rejectionTimestamp, and reapplicationOptions"
    },
    "Validation": "Ensures API successfully rejects the offer and returns the correct response with valid input"
  },
  {
    "ScenarioID": "2",
    "TestName": "testMissingAuthTokenReturns401",
    "Description": "Test rejecting a loan offer without providing an auth token",
    "Execution": {
      "Arrange": "Prepare a valid applicationId without a Bearer token",
      "Act": "Send PUT request to /api/loan-applications/{applicationId}/offer/reject without auth headers",
      "Assert": "Check for 401 status indicating unauthorized access"
    },
    "Validation": "Ensures API requires authentication for rejecting a loan offer"
  },
  {
    "ScenarioID": "3",
    "TestName": "testInvalidAuthTokenReturns401",
    "Description": "Test rejecting a loan offer with an invalid auth token",
    "Execution": {
      "Arrange": "Prepare a valid applicationId and an invalid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/{applicationId}/offer/reject with invalid auth headers",
      "Assert": "Check for 401 status indicating unauthorized access"
    },
    "Validation": "Ensures API rejects requests with invalid authentication tokens"
  },
  {
    "ScenarioID": "4",
    "TestName": "testNonExistentApplicationIdReturns404",
    "Description": "Test rejecting a loan offer with a non-existent applicationId",
    "Execution": {
      "Arrange": "Prepare a non-existent applicationId and a valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/{applicationId}/offer/reject",
      "Assert": "Check for 404 status indicating offer not found or application not approved"
    },
    "Validation": "Ensures API returns 404 for non-existent applicationId"
  },
  {
    "ScenarioID": "5",
    "TestName": "testEmptyApplicationIdReturns404",
    "Description": "Test rejecting a loan offer with an empty applicationId",
    "Execution": {
      "Arrange": "Prepare an empty applicationId and a valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications//offer/reject",
      "Assert": "Check for 404 status indicating offer not found or application not approved"
    },
    "Validation": "Ensures API handles empty applicationId correctly"
  },
  {
    "ScenarioID": "6",
    "TestName": "testInvalidApplicationIdFormatReturns404",
    "Description": "Test rejecting a loan offer with an invalid applicationId format",
    "Execution": {
      "Arrange": "Prepare an applicationId with invalid format (e.g., special characters) and a valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/{invalidApplicationId}/offer/reject",
      "Assert": "Check for 404 status indicating offer not found or application not approved"
    },
    "Validation": "Ensures API handles invalid applicationId format correctly"
  },
  {
    "ScenarioID": "7",
    "TestName": "testValidRequestWithEmptyReapplicationOptions",
    "Description": "Test rejecting a loan offer where the response contains an empty reapplicationOptions array",
    "Execution": {
      "Arrange": "Prepare a valid applicationId and a valid Bearer token",
      "Act": "Send PUT request to /api/loan-applications/{applicationId}/offer/reject",
      "Assert": "Check for 200 status and response body contains confirmationMessage, rejectionTimestamp, and an empty reapplicationOptions array"
    },
    "Validation": "Ensures API correctly handles cases where no reapplication options are available"
  }
]

*/

// ********RoostGPT********
package com.medeiros.RoostTest;
applicationId,baseUrl
import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class ApiLoanapplicationsApplicationIdOfferRejectPutTest {

    List<JSONObject> testCases = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/com/medeiros/RoostTest/api_loan-applications_applicationId_offer_rejectPutTest.JSON");
    }


    @Test
    public void ApiLoanapplicationsApplicationIdOfferRejectPut_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = "{baseUrl}";

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/api/loan-applications/{applicationId}/offer/reject";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "/var/tmp/Roost/RoostGPT/homeloan-AT/b0fc1826-0d80-4c1c-84b2-8595fd39aa80/20251027-073651-roost-vscode-api-musicblender-java-test.yaml";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("put".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "put");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: ApiLoanapplicationsApplicationIdOfferRejectPut_Test\n", testNumber++);
            System.out.println("Request: PUT " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }
}
