// ********RoostGPT********
/*
Test generated by RoostGPT for test homeloan-AT using AI Type Open AI and AI Model gpt-4o

Test generated for /api/support/contact-info_get for http method type GET in rest-assured framework

RoostTestHash=8f763b915b

[
  {
    "ScenarioID": "1",
    "TestName": "testValidRequestReturns200",
    "Description": "Test a valid request to retrieve customer support contact information",
    "Execution": {
      "Arrange": "No parameters required",
      "Act": "Send GET request to /api/support/contact-info",
      "Assert": "Check for 200 status and response body contains valid contact information"
    },
    "Validation": "Ensures API successfully returns correct response with valid input"
  },
  {
    "ScenarioID": "2",
    "TestName": "testResponseContainsPhoneNumbers",
    "Description": "Verify response includes a phoneNumbers array with valid objects",
    "Execution": {
      "Arrange": "No parameters required",
      "Act": "Send GET request to /api/support/contact-info",
      "Assert": "Check that response body contains a non-empty phoneNumbers array with valid type, number, and availability"
    },
    "Validation": "Ensures phoneNumbers array is present and correctly structured"
  },
  {
    "ScenarioID": "3",
    "TestName": "testResponseContainsEmailAddresses",
    "Description": "Verify response includes an emailAddresses array with valid objects",
    "Execution": {
      "Arrange": "No parameters required",
      "Act": "Send GET request to /api/support/contact-info",
      "Assert": "Check that response body contains a non-empty emailAddresses array with valid type, email, and responseTime"
    },
    "Validation": "Ensures emailAddresses array is present and correctly structured"
  },
  {
    "ScenarioID": "4",
    "TestName": "testResponseContainsChatOptions",
    "Description": "Verify response includes a chatOptions array with valid objects",
    "Execution": {
      "Arrange": "No parameters required",
      "Act": "Send GET request to /api/support/contact-info",
      "Assert": "Check that response body contains a non-empty chatOptions array with valid name, url, and availability"
    },
    "Validation": "Ensures chatOptions array is present and correctly structured"
  },
  {
    "ScenarioID": "5",
    "TestName": "testResponseContainsFaqResources",
    "Description": "Verify response includes a faqResources array with valid objects",
    "Execution": {
      "Arrange": "No parameters required",
      "Act": "Send GET request to /api/support/contact-info",
      "Assert": "Check that response body contains a non-empty faqResources array with valid topic and url"
    },
    "Validation": "Ensures faqResources array is present and correctly structured"
  },
  {
    "ScenarioID": "6",
    "TestName": "testEmptyResponseArrays",
    "Description": "Verify response handles empty arrays correctly",
    "Execution": {
      "Arrange": "No parameters required",
      "Act": "Send GET request to /api/support/contact-info",
      "Assert": "Check that response body can contain empty arrays for phoneNumbers, emailAddresses, chatOptions, and faqResources"
    },
    "Validation": "Ensures API can handle and return empty arrays without error"
  },
  {
    "ScenarioID": "7",
    "TestName": "testMalformedRequestPath",
    "Description": "Test malformed request path returns 404",
    "Execution": {
      "Arrange": "No parameters required",
      "Act": "Send GET request to /api/support/contact-infoo",
      "Assert": "Check for 404 status"
    },
    "Validation": "Ensures API returns 404 for incorrect endpoint paths"
  },
  {
    "ScenarioID": "8",
    "TestName": "testInvalidMethodReturns405",
    "Description": "Test using an invalid HTTP method returns 405",
    "Execution": {
      "Arrange": "No parameters required",
      "Act": "Send POST request to /api/support/contact-info",
      "Assert": "Check for 405 status"
    },
    "Validation": "Ensures API returns 405 for unsupported HTTP methods"
  }
]

*/

// ********RoostGPT********
package com.medeiros.RoostTest;
baseUrl
import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class ApiSupportContactinfoGetTest {

    List<JSONObject> testCases = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/com/medeiros/RoostTest/api_support_contact-infoGetTest.JSON");
    }


    @Test
    public void ApiSupportContactinfoGet_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = "{baseUrl}";

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/api/support/contact-info";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "/var/tmp/Roost/RoostGPT/homeloan-AT/b0fc1826-0d80-4c1c-84b2-8595fd39aa80/20251027-073651-roost-vscode-api-musicblender-java-test.yaml";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("get".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "get");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: ApiSupportContactinfoGet_Test\n", testNumber++);
            System.out.println("Request: GET " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }
}
