
// ********RoostGPT********
/*
Test generated by RoostGPT for test UT-Java using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=loginUser_d19666d97a
ROOST_METHOD_SIG_HASH=loginUser_8fe76c816e

Scenario 1: Successful Login with Correct Email and Password

Details:
  TestName: loginUserWithCorrectCredentials
  Description: This test checks if the loginUser method successfully logs in a user when provided with the correct email and password.
Execution:
  Arrange: Set up a mock UserAccRepo to return a User_Credentials object with matching email and password.
  Act: Call the loginUser method with the correct email and password.
  Assert: Verify that the method returns "Logado".
Validation:
  This assertion verifies that the method correctly authenticates a user with valid credentials, ensuring the login functionality works as expected.

Scenario 2: Login Attempt with Incorrect Password

Details:
  TestName: loginUserWithIncorrectPassword
  Description: This test checks the behavior of the loginUser method when the provided password does not match the stored password for the given email.
Execution:
  Arrange: Set up a mock UserAccRepo to return a User_Credentials object with the correct email but a different password.
  Act: Call the loginUser method with the correct email but incorrect password.
  Assert: Verify that the method returns "Senha incorreta".
Validation:
  This assertion ensures that the method correctly identifies and handles incorrect password attempts, maintaining security by not allowing access.

Scenario 3: Login Attempt with Non-Existent Email

Details:
  TestName: loginUserWithNonExistentEmail
  Description: This test checks the behavior of the loginUser method when the provided email does not exist in the repository.
Execution:
  Arrange: Set up a mock UserAccRepo to return null when searching for a non-existent email.
  Act: Call the loginUser method with a non-existent email.
  Assert: Verify that the method returns "Email não encontrado!".
Validation:
  This assertion ensures that the method correctly handles login attempts with emails not present in the system, preventing unauthorized access.

Scenario 4: Login Attempt with Null Email

Details:
  TestName: loginUserWithNullEmail
  Description: This test checks the behavior of the loginUser method when the email parameter is null.
Execution:
  Arrange: Set up a mock UserAccRepo to handle null input gracefully.
  Act: Call the loginUser method with a null email.
  Assert: Verify that the method returns "Email não encontrado!".
Validation:
  This assertion ensures that the method can handle null inputs for the email parameter without causing unexpected errors or crashes.

Scenario 5: Login Attempt with Null Password

Details:
  TestName: loginUserWithNullPassword
  Description: This test checks the behavior of the loginUser method when the password parameter is null.
Execution:
  Arrange: Set up a mock UserAccRepo to return a User_Credentials object with a valid email.
  Act: Call the loginUser method with a valid email and null password.
  Assert: Verify that the method returns "Senha incorreta".
Validation:
  This assertion ensures that the method can handle null inputs for the password parameter, maintaining security by not allowing access with null passwords.

Scenario 6: Login Attempt with Empty Email and Password

Details:
  TestName: loginUserWithEmptyEmailAndPassword
  Description: This test checks the behavior of the loginUser method when both email and password parameters are empty strings.
Execution:
  Arrange: Set up a mock UserAccRepo to handle empty string inputs.
  Act: Call the loginUser method with empty email and password.
  Assert: Verify that the method returns "Email não encontrado!".
Validation:
  This assertion ensures that the method correctly handles empty string inputs, preventing unauthorized access and maintaining system integrity.

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.User_Credentials;
import com.medeiros.SPRINGProject.Security.JwtUtil;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import com.medeiros.SPRINGProject.Models.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import java.util.Objects;

class AuthControllerLoginUserTest {

	@Mock
	private UserAccRepository UserAccRepo;

	@InjectMocks
	private AuthController authController;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
	}

	@Test
	@Tag("valid")
	public void loginUserWithCorrectCredentials() {
		String email = "test@example.com"; // TODO: Change to a valid email
		String password = "correctPassword"; // TODO: Change to a valid password
		User_Credentials user = new User_Credentials(email, password, "testUser");
		when(UserAccRepo.findUserByEmail(email)).thenReturn(user);
		String result = authController.loginUser(email, password);
		assertEquals("Logado", result);
	}

	@Test
	@Tag("invalid")
	public void loginUserWithIncorrectPassword() {
		String email = "test@example.com"; // TODO: Change to a valid email
		String password = "incorrectPassword"; // TODO: Change to an invalid password
		User_Credentials user = new User_Credentials(email, "correctPassword", "testUser");
		when(UserAccRepo.findUserByEmail(email)).thenReturn(user);
		String result = authController.loginUser(email, password);
		assertEquals("Senha incorreta", result);
	}

	@Test
	@Tag("invalid")
	public void loginUserWithNonExistentEmail() {
		String email = "nonexistent@example.com"; // TODO: Change to a non-existent email
		when(UserAccRepo.findUserByEmail(email)).thenReturn(null);
		String result = authController.loginUser(email, "anyPassword");
		assertEquals("Email não encontrado!", result);
	}

	@Test
	@Tag("invalid")
	public void loginUserWithNullEmail() {
		String email = null;
		when(UserAccRepo.findUserByEmail(email)).thenReturn(null);
		String result = authController.loginUser(email, "anyPassword");
		assertEquals("Email não encontrado!", result);
	}

	@Test
	@Tag("invalid")
	public void loginUserWithNullPassword() {
		String email = "test@example.com"; // TODO: Change to a valid email
		String password = null;
		User_Credentials user = new User_Credentials(email, "correctPassword", "testUser");
		when(UserAccRepo.findUserByEmail(email)).thenReturn(user);
		String result = authController.loginUser(email, password);
		assertEquals("Senha incorreta", result);
	}

	@Test
	@Tag("invalid")
	public void loginUserWithEmptyEmailAndPassword() {
		String email = "";
		String password = "";
		when(UserAccRepo.findUserByEmail(email)).thenReturn(null);
		String result = authController.loginUser(email, password);
		assertEquals("Email não encontrado!", result);
	}

}