
// ********RoostGPT********
/*
Test generated by RoostGPT for test UT-Java using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=getUserName_2f305a5b83
ROOST_METHOD_SIG_HASH=getUserName_e910087e84

Scenario 1: Valid Token with Correct Claims

Details:
  TestName: validTokenWithCorrectClaims
  Description: This test checks if the getUserName method correctly extracts the username from a valid token with correct claims.
Execution:
  Arrange: Create a valid JWT token with a known username as the subject. Ensure the token is signed with the correct secret key.
  Act: Call the getUserName method with the valid token.
  Assert: Use JUnit assertions to verify that the returned username matches the expected username.
Validation:
  This assertion verifies that the method correctly parses a valid token and retrieves the username. It ensures the method's functionality in normal operation with valid input.

Scenario 2: Invalid Token with Incorrect Signature

Details:
  TestName: invalidTokenWithIncorrectSignature
  Description: This test checks the behavior of the getUserName method when provided with a token that has an incorrect signature.
Execution:
  Arrange: Create a JWT token with a known username but sign it with an incorrect secret key.
  Act: Call the getUserName method with the invalid token.
  Assert: Use JUnit assertions to verify that the method returns null.
Validation:
  This test ensures that the method does not extract a username from a token with an invalid signature, maintaining security by rejecting tampered tokens.

Scenario 3: Expired Token

Details:
  TestName: expiredToken
  Description: This test checks the behavior of the getUserName method when provided with an expired token.
Execution:
  Arrange: Create a JWT token with a known username and set its expiration date in the past.
  Act: Call the getUserName method with the expired token.
  Assert: Use JUnit assertions to verify that the method returns null.
Validation:
  This test confirms that the method correctly handles expired tokens by not returning a username, ensuring expired tokens are not mistakenly accepted.

Scenario 4: Null Token

Details:
  TestName: nullToken
  Description: This test checks the behavior of the getUserName method when provided with a null token.
Execution:
  Arrange: Set the token parameter to null.
  Act: Call the getUserName method with the null token.
  Assert: Use JUnit assertions to verify that the method returns null.
Validation:
  This test ensures that the method gracefully handles null input without throwing exceptions, maintaining robustness against invalid input.

Scenario 5: Empty Token String

Details:
  TestName: emptyTokenString
  Description: This test checks the behavior of the getUserName method when provided with an empty string as the token.
Execution:
  Arrange: Set the token parameter to an empty string.
  Act: Call the getUserName method with the empty token.
  Assert: Use JUnit assertions to verify that the method returns null.
Validation:
  This test confirms that the method does not attempt to parse an empty token string, ensuring it handles edge cases of invalid input correctly.

Scenario 6: Token with No Subject Claim

Details:
  TestName: tokenWithNoSubjectClaim
  Description: This test checks the behavior of the getUserName method when provided with a token that lacks a subject claim.
Execution:
  Arrange: Create a JWT token without setting a subject claim.
  Act: Call the getUserName method with the token lacking a subject.
  Assert: Use JUnit assertions to verify that the method returns null.
Validation:
  This test ensures that the method does not return a username when the token lacks a subject claim, maintaining the integrity of the extracted data.

*/

// ********RoostGPT********
package com.medeiros.SPRINGProject.Security;

import com.medeiros.SPRINGProject.Models.User_Credentials;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.security.core.Authentication;
import java.nio.charset.StandardCharsets;
import java.security.Key;
import java.util.Date;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

public class JwtUtilGetUserNameTest {

	private JwtUtil jwtUtil;

	private String jwtSecret = "mySecretKeymySecretKeymySecretKeymySecretKey"; // TODO:
																				// Replace
																				// with
																				// actual
																				// secret
																				// key

	private Long jwtExpirationMilliseg = 3600000L; // 1 hour

	@BeforeEach
	public void setUp() {
		jwtUtil = Mockito.spy(new JwtUtil());
		// Use reflection to set private fields
		try {
			java.lang.reflect.Field secretField = JwtUtil.class.getDeclaredField("jwtSecret");
			secretField.setAccessible(true);
			secretField.set(jwtUtil, jwtSecret);
			java.lang.reflect.Field expirationField = JwtUtil.class.getDeclaredField("jwtExpirationMilliseg");
			expirationField.setAccessible(true);
			expirationField.set(jwtUtil, jwtExpirationMilliseg);
		}
		catch (NoSuchFieldException | IllegalAccessException e) {
			e.printStackTrace();
		}
	}

	@Test
	@Tag("valid")
	public void validTokenWithCorrectClaims() {
		// Arrange
		Authentication authentication = mock(Authentication.class);
		User_Credentials user = mock(User_Credentials.class);
		when(authentication.getPrincipal()).thenReturn(user);
		when(user.getUsername()).thenReturn("testUser");
		String token = jwtUtil.newToken(authentication);
		// Act
		String username = jwtUtil.getUserName(token);
		// Assert
		assertEquals("testUser", username);
	}

	@Test
	@Tag("invalid")
	public void invalidTokenWithIncorrectSignature() {
		// Arrange
		String token = Jwts.builder()
			.setSubject("testUser")
			.signWith(Keys.hmacShaKeyFor("wrongSecretKeywrongSecretKeywrongSecretKey".getBytes(StandardCharsets.UTF_8)))
			.compact();
		// Act
		String username = jwtUtil.getUserName(token);
		// Assert
		assertNull(username);
	}

	@Test
	@Tag("invalid")
	public void expiredToken() {
		// Arrange
		Key secretKey = Keys.hmacShaKeyFor(jwtSecret.getBytes(StandardCharsets.UTF_8));
		String token = Jwts.builder()
			.setSubject("testUser")
			.setExpiration(new Date(System.currentTimeMillis() - 1000)) // Expired 1
																		// second ago
			.signWith(secretKey)
			.compact();
		// Act
		String username = jwtUtil.getUserName(token);
		// Assert
		assertNull(username);
	}

	@Test
	@Tag("invalid")
	public void nullToken() {
		// Act
		String username = jwtUtil.getUserName(null);
		// Assert
		assertNull(username);
	}

	@Test
	@Tag("invalid")
	public void emptyTokenString() {
		// Act
		String username = jwtUtil.getUserName("");
		// Assert
		assertNull(username);
	}

	@Test
	@Tag("invalid")
	public void tokenWithNoSubjectClaim() {
		// Arrange
		Key secretKey = Keys.hmacShaKeyFor(jwtSecret.getBytes(StandardCharsets.UTF_8));
		String token = Jwts.builder().signWith(secretKey).compact();
		// Act
		String username = jwtUtil.getUserName(token);
		// Assert
		assertNull(username);
	}

}